## NUMPY PRACTICE WORK

In [1]:
import numpy as np

### CREATING ARRAYS

In [3]:
list1 = [0,1,2,3,4,5,8,9]
list1

[0, 1, 2, 3, 4, 5, 8, 9]

In [5]:
array = np.array(list1) 

In [6]:
array

array([0, 1, 2, 3, 4, 5, 8, 9])

In [8]:
np.arange(0,15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(0,15,2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [10]:
np.zeros((5,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.random.randint(0,20)

3

In [16]:
np.random.randint(0,20,(4,5)) 

array([[12,  9,  7, 18,  9],
       [16,  8,  4, 12, 12],
       [10,  1, 11, 17,  9],
       [15, 19, 18,  2,  2]])

### OPERATIONS

In [17]:
a = np.random.randint(0,100,10)
a

array([ 5, 70,  9, 72, 91, 73, 66, 16, 69, 17])

In [20]:
np.random.seed() # watch video for details
arr = np.random.randint(0,80,9)

In [21]:
arr

array([15, 34, 23, 46, 13, 47, 69, 28, 11])

In [22]:
arr2 = np.random.randint(0,100,10)

In [23]:
arr2

array([13,  8, 58,  4, 97,  0,  6, 81,  3, 39])

In [24]:
arr

array([15, 34, 23, 46, 13, 47, 69, 28, 11])

In [25]:
arr.max() 

69

In [26]:
arr.min()

11

In [27]:
arr.mean()

31.77777777777778

In [31]:
arr.reshape(3,3)

array([[15, 34, 23],
       [46, 13, 47],
       [69, 28, 11]])

### INDEXING

In [32]:
mat = np.arange(0,100).reshape(10,10)

In [33]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
row = 8
col = 5

In [36]:
mat[row,col]

85

In [37]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
# With Slices
mat[:,col] 

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [39]:
mat[row,:]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [40]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

### MASKING

In [41]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
mat > 40

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [45]:
mat[mat>60] 

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])